# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js:
  - 10.16.3
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "D-107"
  - git config user.email "m@m-finder.com"
  - git add .
  - git commit -m "Travis ci push"
  - git push --force --quiet "https://${travis_token}@${gh_repo}" master:master
env:
  global:
    - gh_repo: github.com/d-107/d-107.github.io.git
# End: Build LifeCycle
